version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "12:00"
      timezone: "UTC"      
      
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
