# .golangci.yml for https://github.com/fxamacker/cbor
# Updated on May 10, 2026.
version: "2"

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/fxamacker/cbor

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - depguard
    - dogsled
    - dupword
    - errcheck
    - exptostd
    - forbidigo
    - goconst
    - gocritic
    - gocyclo
    - godoclint
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - intrange
    - misspell
    - nilnesserr
    - perfsprint
    - predeclared
    - reassign
    - revive
    - staticcheck
    - unconvert
    - unused
    - usestdlibvars
    - wastedassign
  settings:
    depguard:
      rules:
        prevent_unmaintained_packages:
          list-mode: strict
          files:
            - $all
            - '!$test'
          allow:
            - $gostd
            - github.com/x448/float16
    dupl:
      threshold: 100
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - commentedOutCode
        - dupImport
        - ifElseChain
        - octalLiteral
        - paramTypeCombine
        - whyNoLint
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    govet:
      enable:
        - deepequalerrors
        - nilness
        - reflectvaluecompare
        - shadow
        - sortslice
        - unusedwrite
    lll:
      line-length: 140
    misspell:
      locale: US
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: decode.go
        text: string ` overflows ` has (\d+) occurrences, make it a constant
      - path: decode.go
        text: string ` \(range is \[` has (\d+) occurrences, make it a constant
      - path: decode.go
        text: string `, ` has (\d+) occurrences, make it a constant
      - path: decode.go
        text: string ` overflows Go's int64` has (\d+) occurrences, make it a constant
      - path: decode.go
        text: string `\]\)` has (\d+) occurrences, make it a constant
      - path: valid.go
        text: string ` for type ` has (\d+) occurrences, make it a constant
      - path: valid.go
        text: 'string `cbor: ` has (\d+) occurrences, make it a constant'
      - linters:
          - goconst
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$

