# GitHub Actions workflow for govulncheck.
# This file is licensed under MIT License.
# https://github.com/fxamacker/cbor

name: govulncheck

# Revoke default permissions and grant what's needed in each job.
permissions: {}

on:
  workflow_dispatch:
  pull_request:
    # Run govulncheck on PR for all branches and paths.
  push:
    # Run govulncheck on push for all branches and paths.
  schedule:
    - cron: '45 12 * * *' # Daily at 12:45 UTC / 7:45 AM Central

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  Check:
    runs-on: ubuntu-latest
    permissions:
      # Grant permission to read content.
      contents: read
    steps:
    - name: Checkout source
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        fetch-depth: 1

    - name: Install Go and setup env
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
      with:
        go-version: 1.26
        check-latest: true
 
    - name: Install latest govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@0782b76014f15f24e22a438f30f308df42899ba1 # v1.3.0

    - name: Run govulncheck
      run: govulncheck -show=traces ./...
